### ISSUE TITLE
Fence not being recognized

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#10]
The TeX code `(x-y)^2` produces the MathML

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mo stretchy="false">(</mo>
  <mi>x</mi>
  <mo>&#x2212;<!-- − --></mo>
  <mi>y</mi>
  <msup>
    <mo stretchy="false">)</mo>
    <mn>2</mn>
  </msup>
</math>
```

Here the close parenthesis is an embellished operator (embellished by the square).  I would expect the semantic rendering to pick up on the fact that this is an embellished fence and still make a fence object with the open parenthesis.  (It doesn't.)

I understand that the `<msup>` should really be around the whole parenthesized term, but that is not the way TeX works, and the TeX input jax doesn't do semantic analysis to do things like match pairs of fences that don't use `\left...\right`.  We will, no doubt, see lots of this kind of thing in the wild, so it would be great of the semantic analysis could match these up.

You may also want to think about actually moving the `<msup>` rather than keeping it as an embellished operator.  That is certainly more destructive to the original MathML, but I was hoping that this kind of thing was part of what we would be able to achieve.

Thoughts?

**Comment by pkra** [comment]
>  That is certainly more destructive to the original MathML, but I was hoping that this kind of thing was part of what we would be able to achieve.

:+1:  I think matching fences would be a very desirable effect.

**Comment by zorkow** [comment]
Ahh... That's one of those skeletons in my closet! I believe it is a long
standing todo notes.
There are actually a number of issus attached:
Do we want to have the same treatment for neutral fences? Possibly
interfering with certain notations for definite integrals.
What if we do not have a matching (opening) fence? Or what if we have a
closing fence with a superscript.
What about subscripts?

A quick and dirty solution would be to take care of fence + superscript by
trying to match fence, if that can't be done assume superscript is indeed
part of the fence, only.

**Comment by dpvc** [comment]
> Do we want to have the same treatment for neutral fences?

There are two ways to think about it.  The straight-forward one is to say that an embellished operator with a fence at its core should be treated as that fence operator would if not embellished (this is how MathML treats them for stretching and spacing, for example).  So matching the right-paren-with-square to the left-paren would follow from that.  I think that SRE should do at least that much.

The second approach would be to try to recognize the semantics underlying the markup and convert

``` html
<math>
  <mo stretchy="false">(</mo>
  <mi>x</mi>
  <mo>&#x2212;</mo>
  <mi>y</mi>
  <msup>
    <mo stretchy="false">)</mo>
    <mn>2</mn>
  </msup>
</math>
```

to 

``` html
<math>
  <msup>
    <mrow>
      <mo stretchy="false">(</mo>
      <mi>x</mi>
      <mo>&#x2212;</mo>
      <mi>y</mi>
      <mo stretchy="false">)</mo>
    </mrow>
    <mn>2</mn>
  </msup>
</math>
```

(with the enrichments, of course).  That is, recognize the square on the parenthesis as really applying to the whole fenced operation, not just the right parenthesis.  That does change the original MathML in a non-trivial way.

This is the kind of analysis that I hoped SRE will be able to perform, as the TeX input jax really can't do that itself.  Do you think that something like that can be done?

I originally ran into this trying to collapse `\sum_{i=1}^N (x_i-\mu)^2`, but the sum ended up producing

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" type="punctuated" role="sequence" id="21" children="17,7,20" content="7">
  <mrow type="bigop" role="sum" id="17" children="6,16" content="0" parent="21">
    <munderover type="limboth" role="sum" id="6" children="0,4,5" parent="17">
      <mo type="largeop" role="sum" id="0" parent="17" operator="bigop">&#x2211;</mo>
      <mrow class="MJX-TeXAtom-ORD" type="relseq" role="equality" id="4" children="1,3" content="2" parent="6">
        <mi type="identifier" role="latinletter" id="1" parent="4">i</mi>
        <mo type="relation" role="equality" id="2" parent="4" operator="relseq,=">=</mo>
        <mn type="number" role="integer" id="3" parent="4">1</mn>
      </mrow>
      <mi type="identifier" role="latinletter" id="5" parent="6">N</mi>
    </munderover>
    <mrow type="empty" role="unknown" id="16" parent="17" />
  </mrow>
  <mo stretchy="false" type="punctuation" role="openfence" id="7" parent="21" operator="punctuated">(</mo>
  <mrow type="infixop" role="subtraction" id="20" children="10,19" content="11" parent="21">
    <msub type="subscript" role="latinletter" id="10" children="8,9" parent="20">
      <mi type="identifier" role="latinletter" id="8" parent="10">x</mi>
      <mi type="identifier" role="latinletter" id="9" parent="10">i</mi>
    </msub>
    <mo type="operator" role="subtraction" id="11" parent="20" operator="infixop,&#x2212;">&#x2212;</mo>
    <mrow type="infixop" role="implicit" id="19" children="12,15" content="18" parent="20">
      <mi type="identifier" role="greekletter" id="12" parent="19">&#x3BC;</mi>
      <mo type="operator" role="multiplication" id="18" parent="19" added="true" operator="infixop,&#x2062;">&#x2062;</mo>
      <msup type="superscript" role="close" id="15" children="13,14" parent="19">
        <mo stretchy="false" type="fence" role="close" id="13" parent="15">)</mo>
        <mn type="number" role="integer" id="14" parent="15">2</mn>
      </msup>
    </mrow>
  </mrow>
</math>
```

which applies the sum to an empty argument, fails to match the fence, and makes `\mu)^2` into a product.  So the formula collapsing becomes really strange.

**Comment by dpvc** [comment]
> What if we do not have a matching (opening) fence?

Then I guess you proceed as you would for an unmatched fence without embellishment.

> Or what if we have a  closing fence with a superscript.  What about subscripts?

As embellished operators, I'd treat them as you would the core element.  This would also be true for other types of embellishment (like extra `<mrow>`, or `<mpadded>`, or other enclosures that form embellished operators as defined in the spec).  

>  Possibly interfering with certain notations for definite integrals.

I'm not sure what you have in mind, here.  Can you give examples of what you mean?

**Comment by zorkow** [comment]
Here's an example, taken straight from Wikipedia (German):
 [F(x)]_a^b = [F(x)]_{x=a}^{x=b} = F(x)\Big|_a^b = F(x)\Big|_{x=a}^{x=b}

The right two expression I (and possibly most other authors) would have achieved by using a \left. and \right|. 
Anyway, the next complication is then when your F is actually an absolute value function. Not unusual when teaching integration of functions that non-differentiable in a point.

> This is the kind of analysis that I hoped SRE will be able to perform, as the TeX input jax really can't do that itself. Do you think that something like that can be done?

Can indeed be done. But as it is more an issue of interpretation, than most others, I always had postponed a decision. So we should come up with what is the most pragmatic choice and put in a rule for this. 

I will put together some of the cases to consider in the grammar document and then we can make final decision on what exactly we want.

**Comment by zorkow** [comment]
Completed with commit 7cddad6dc069df5090d6d693f10420b7e9d768dd
