### ISSUE TITLE
mmultiscripts and nones

### ISSUE THREAD

**Issue by zorkow** [zorkow/speech-rule-engine#11]
@dpvc
mmultiscripts works now. I've tested all corner cases I can think of, but exclusively with MathML expressions.  If you have time, please throw some LaTeX at it. 

The only issue left is none existing nones. Semantically we represent them as empty nodes, but they are not explicitly added to the enriched structure. Example:

```html
<math>
  <mmultiscripts>
    <mi>A</mi>
    <none/>
    <mn>2</mn>
    <mprescripts/>
    <mn>3</mn>
  </mmultiscripts>
</math>

```

Semantic Tree:
```html
<stree>
  <tensor role="unknown" id="5">
    <children>
      <identifier role="latinletter" font="italic" id="0">A</identifier>
      <number role="leftsub" font="normal" id="1">3</number>
      <empty role="leftsuper" id="2"/>
      <empty role="rightsub" id="3"/>
      <number role="rightsuper" font="normal" id="4">2</number>
    </children>
  </tensor>
</stree>

```

Semantically enriched MathML:
```html
<math>
  <mmultiscripts type="tensor" role="unknown" id="5" children="0,1,2,3,4">
    <mi type="identifier" role="latinletter" id="0" parent="5">A</mi>
    <none type="empty" role="rightsub" id="3" parent="5"/>
    <mn type="number" role="rightsuper" id="4" parent="5">2</mn>
    <mprescripts/>
    <mn type="number" role="leftsub" id="1" parent="5">3</mn>
  </mmultiscripts>
</math>

```

**Comment by dpvc** [comment]
It turns out that the TeX input jax never produces mmultiscripts (the HTML-CSS output didn't implement it initially), so I can't really use TeX to test this.

> The only issue left is none existing nones.

I'm not sure what that means.  But the enriched version given above works fine with MathJax, so I don't think there is a problem.

**Comment by zorkow** [comment]
>> The only issue left is none existing nones.

> I'm not sure what that means. But the enriched version given above works fine with MathJax, so I don't  think there is a problem.

In the example only one of the <none/>s is in the original MathML. Semantically we fill in all the four corners. I.e., what's <none/> or missing gets an empty node. Currently the left super is dropped in the enrichment, leading to the dangling child pointer 2.

**Comment by dpvc** [comment]
I see now.  I had just looked at the MathML not the ID's in the data-semantic attributes, so missed the inconsistency.  Is it not possible to drop the 2 from the children attribute as well?  (Or put in a `<none>` for it?)

**Comment by zorkow** [comment]
This now works as expected.
Original none elements remain in place, potentially new ones are added. 
Child pointers are now of variable length pointing to the single indices and collapsed attribute contains the information on the semantic structure:

```html
<math>
  <mmultiscripts>
    <mi>A</mi>
    <mn>3</mn>
    <none/>
    <mi>k</mi>
    <mi>l</mi>
    <mprescripts/>
    <mn>1</mn>
    <none/>
    <none/>
    <mi>j</mi>
  </mmultiscripts>
</math>

```

becomes

```html
<math>
  <mmultiscripts type="tensor" role="unknown" id="17" children="1,2,5,6,9,10,13,14" collapsed="(17 (4 1 2) (8 5 6) (12 9 10) (16 13 14))">
    <mi type="identifier" role="latinletter" id="0" parent="17">A</mi>
    <mn type="number" role="rightsub" id="9" parent="17">3</mn>
    <none type="empty" role="rightsuper" id="13" parent="17"/>
    <mi type="identifier" role="rightsub" id="10" parent="17">k</mi>
    <mi type="identifier" role="rightsuper" id="14" parent="17">l</mi>
    <mprescripts/>
    <mn type="number" role="leftsub" id="1" parent="17">1</mn>
    <none type="empty" role="leftsuper" id="5" parent="17"/>
    <none type="empty" role="leftsub" id="2" parent="17"/>
    <mi type="identifier" role="leftsuper" id="6" parent="17">j</mi>
  </mmultiscripts>
</math>

```

Not yet working properly are special cases where only the base or only right scripts are given, as SRE rewrites those.

**Comment by zorkow** [comment]
All cases for multiscripts are now fully working.
