### ISSUE TITLE
ms elements end up blank

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#12]
The input

``` html
<math display="block">
<ms>abc</ms>
</math>
```

generates

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <ms type="unknown" role="unknown" id="0"></ms>
</math>
```

where the text of the `<ms>` element has been lost.

**Comment by zorkow** [comment]
Fixed. PTAL.
There is no semantic treatment of the quot attributes.

**Comment by dpvc** [comment]
Great.  Looks good, thanks!

> There is no semantic treatment of the quot attributes.

Right, I didn't expect there would be.
