### ISSUE TITLE
Presence of space causes <mrow> rather than <math>

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#14]
The input

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>a</mi>
  <mspace/>
</math>
```

generates

``` html
<mi type="identifier" role="latinletter" id="0">a</mi>
```

with no `<math>` element.  Removing the `<mspace/>` resolves the problem.

**Comment by zorkow** [comment]
Fixed. PTAL.

**Comment by zorkow** [comment]
All elements that are semantically ignore (mphantom, merror etc.) should now remain in their correct place. Spaces are still only ignored.
