### ISSUE TITLE
mglpyhs causing (unproblematic) error

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#165]
E.g.,

```
var sre = require("speech-rule-engine@2.0.0-beta.3")
let speechConfig = {
        semantics: true,
        domain: 'mathspeak',
        style: 'default'
        };
sre.setupEngine(speechConfig);
sre.toSpeech(`
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mglyph src="my-braid-23.png"/></math>`)
```

will log out 

`"Parse Error: this.getFactory is not a function"`

SRE still returns a result so this is not critical.

**Comment by pkra** [comment]
(Note that there's also #80 )

**Comment by zorkow** [comment]
Yes, a deja vu...
But the example is helpful. Is there a chance of glyphs having some meaningful alt text?
My current solution would be to simply retain the alt text or otherwise ignore.

@dpvc I remember we've discussed this case before. Would there be any other useful information I could extract?

**Comment by zorkow** [comment]
I have found the bug that causes the error message.
For the time being an mglyph will be ignored. I will leave it at that for v2 and fix it once we have a better solution how to deal with arbitrary glyphs. 
Do you have any real world examples for that?

**Comment by pkra** [comment]
> Is there a chance of glyphs having some meaningful alt text?

Yes. In #80 I suggested that SRE should pick that up (plus some kind of default string)

> Do you have any real world examples for that?

Yes. E.g., anytime xypic or tikz is used within math mode, I end up getting some math with an mglyph (or more precisely, TeX with an `\img` macro).

Quick check gets me ~150 mglyphs in ~30 published articles.

**Comment by dpvc** [comment]
> Is there a chance of glyphs having some meaningful alt text?

Agreed, that is technically a required attribute, and is the place where the readable text should be put.  The only other place that there is any information is in the `src` attribute, which would give the name of the file used.  If there is no `alt` attribute, you could pull the file name out of the URL and use that, I suppose, as at least better than nothing.  "Image named ..." or something.

**Comment by pkra** [comment]
> you could pull the file name out of the URL

That's what some screenreaders do automatically and it's generally considered problematic. For example, from http://webaim.org/blog/alt-text-and-linked-images/

> As a result, screen readers will typically read either the image file name or the URL of the page being linked to. In most cases, this is of little or no value to the user – or even worse, it makes the page even more inaccessible than if the link and image had been ignored altogether.

I think in the case of missing alt text an honest "image without alt text" is best.

**Comment by zorkow** [comment]
Still I am not sure how one would semantically treat it.  I'd probably just treat it as an identifier.
Then something like this 

```
  <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi>a</mi>
      <mglyph src="my-braid-23.png"/>
      <mn>1</mn>
  </math>
```
would become ```a times braid times 1```. Although the braid is probably more an operator.

**Comment by dpvc** [comment]
I'm not sure where you got the "braid" from, unless it was from the `src` attribute, which Peter has indicated might not be the best idea.

> Although the braid is probably more an operator

That should be marked up as

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi>a</mi>
      <mo><mglyph src="my-braid-23.png"/></mo>
      <mn>1</mn>
  </math>
```

(recall that `<mglyph>` is allowed to be a child of a token element).  If the `mglyph` appears outside of an `mo`, I would probably consider it to be in an implicit `mi`.

**Comment by pkra** [comment]
>  If the mglyph appears outside of an mo, I would probably consider it to be in an implicit mi.

:+1:

**Comment by zorkow** [comment]
The braid comes from Peter's original example. So mglyph can effectively be any token element or a part of any token element, as well as occur on its own?
So something like <mn>1<mglyph src="my-2.png"/>3</mn> could actually happen. That's really nasty...
I'll have to think about how to include this in the semantic tree.

@dpvc I remember you showed me a couple of examples before. Can you send me again the pointer?

**Comment by dpvc** [comment]
> you showed me a couple of examples before. Can you send me again the pointer?

The only one I know of is in the [MathML 3.0 documentation](https://www.w3.org/TR/MathML3/chapter3.html#id.3.2.1.2.3).  This is where the braid images came from.  The only other usage I've seen involves using the `<semantics>` hack that incorrectly uses `<annotation-xml>` elements as the first child (it is supposed to be a presentation MathML element).  Firefox would render that anyway, so this became a known hack to include images.  The should be handled via `<mglyph>`, I would think.  Here's one [example](https://golem.ph.utexas.edu/~distler/blog/archives/001475.html).

Here are two examples that use data URIs to load an SVG image:

```
<math>
<mglyph src='data:image/svg+xml,
    <svg xmlns="http://www.w3.org/2000/svg" height="42px" width="42px">
      <rect stroke="black" fill="none" rx="5px" width="40px" height="40px"></rect>
      <circle stroke="black" fill="black" cy="30px" cx="30px" r="5px"></circle>
      <circle stroke="black" fill="black" cy="30px" cx="10px" r="5px"></circle>
      <circle stroke="black" fill="black" cy="20px" cx="20px" r="5px"></circle>
      <circle stroke="black" fill="black" cy="10px" cx="30px" r="5px"></circle>
      <circle stroke="black" fill="black" cy="10px" cx="10px" r="5px"></circle>
    </svg>'></mglyph>
</math>
```
and
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mglyph src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iNDJweCIgd2lkdGg9IjQycHgiPiAgPHJlY3Qgc3Ryb2tlPSJibGFjayIgZmlsbD0ibm9uZSIgcng9IjVweCIgd2lkdGg9IjQwcHgiIGhlaWdodD0iNDBweCI+PC9yZWN0PiAgPGNpcmNsZSBzdHJva2U9ImJsYWNrIiBmaWxsPSJibGFjayIgY3k9IjMwcHgiIGN4PSIzMHB4IiByPSI1cHgiPjwvY2lyY2xlPiAgPGNpcmNsZSBzdHJva2U9ImJsYWNrIiBmaWxsPSJibGFjayIgY3k9IjMwcHgiIGN4PSIxMHB4IiByPSI1cHgiPjwvY2lyY2xlPiAgPGNpcmNsZSBzdHJva2U9ImJsYWNrIiBmaWxsPSJibGFjayIgY3k9IjIwcHgiIGN4PSIyMHB4IiByPSI1cHgiPjwvY2lyY2xlPiAgPGNpcmNsZSBzdHJva2U9ImJsYWNrIiBmaWxsPSJibGFjayIgY3k9IjEwcHgiIGN4PSIzMHB4IiByPSI1cHgiPjwvY2lyY2xlPiAgPGNpcmNsZSBzdHJva2U9ImJsYWNrIiBmaWxsPSJibGFjayIgY3k9IjEwcHgiIGN4PSIxMHB4IiByPSI1cHgiPjwvY2lyY2xlPjwvc3ZnPg=="></mglyph>
</math>
```

**Comment by pkra** [comment]
> Can you send me again the pointer?

The MathML test suite has 9 (artificial) examples, starting at  https://www.w3.org/Math/testsuite/build/main/Presentation/TokenElements/mglyph/mglyph3-full.xhtml.

I will send you real-world examples by email.

On thinking more about it, I think an implicit `mtext` is probably better than an implicit `mi` as useful alt text will more likely be similar to `mtext` content.

**Comment by pkra** [comment]
I think this issue was fixed.
