### ISSUE TITLE
Adding Braille to Speech Rule Engine

### ISSUE THREAD

**Issue by Kevin-Morales** [zorkow/speech-rule-engine#178]
I would like to see Braille support for tools like these. Furthermore, I would like to contribute such support but I would like to know if there is interest in supporting Braille, if you accept contributions of this kind, and how to get started on developing for this project. Is there anything else to be known besides what is on the readme instruction?

Kind Regards,
Kevin Morales

**Comment by zorkow** [comment]
Hi Kevin,
Braille support is indeed on our road map. There are some initial steps towards this in the [Braille table branch](https://github.com/zorkow/speech-rule-engine/tree/Braille_table). However, I am not planning to start before end of Autumn. If you want to contribute we should have a face to face discussion some time after the summer.
Best,
Volker

**Comment by Kevin-Morales** [comment]
Hello Volker,

Thanks so much for your reply. Yes, I'd like to set up a time for conversing after the summer. In the meantime, I'll learn my way around the code and look at the referenced branch. I'm actually familiar with the Braille system, as I am completely blind.

Kind Regards,
Kevin

**Comment by zorkow** [comment]
Kevin,
Are you still interested in contributing to this? It took me longer than expected to get back to this but I would like to give it a go in the New Year.
Best,
Volker

**Comment by Kevin-Morales** [comment]
Hello Volker,

Yes, I'm definitely interested in contributing still.

Kind Regards,
Kevin

**Comment by pkra** [comment]
I believe this issue can be closed as resolved in v3+.

**Comment by zorkow** [comment]
Nemeth integration since v3.0
