### ISSUE TITLE
Using an html5 file with mml for conversion results in spaces between mml tags getting converted to "ampersand nbsp semicolon" 

### ISSUE THREAD

**Issue by nirupa-kumar** [zorkow/speech-rule-engine#18]
This was previously raised as an issue on MathJax-node and after discussion , determined to be part of the Speech Rule Engine. 
https://github.com/mathjax/MathJax-node/issues/118

If there are non-breaking spaces in an html file , that gets converted to ampersand nbsp semicolon as part of the description. 
Please let me know if you need any further information.

**Comment by zorkow** [comment]
I've chucked mapping for named HTML character entity references long ago, as they would be translated to the corresponding unicode character by browsers/jsdom. Apparently that is not correct for &nbsp; and maybe others. I will look into what I will need to reintroduce.

**Comment by nirupa-kumar** [comment]
@zorkow :Thanks for keeping us posted.

**Comment by zorkow** [comment]
The general problem is that SRE expects valid XML as input. &nbsp; is not a valid XML entity reference (&lt; or &gt; are of instance), so it is not correctly translated by xmldom.

I have now fixed this for the particular case and published a new release via npm. 
For the future, we should consider the question, do we need to treat the general case? I.e., all possible HTML entity references that are not XML entity references.

**Comment by pkra** [comment]
> For the future, we should consider the question, do we need to treat the general case?

This seems to relate to the long-standing issues on the MathJax end how to (whether or not to?) switch from XML parsing to HTML parsing and how to improve handling of mixed content (HTML in MathML or several linked MathML pieces in HTML -- think of `\intertext`, nested subequations).
