### ISSUE TITLE
Negative sign in front of a fraction is referred to as minus vs. negative. 

### ISSUE THREAD

**Issue by nirupa-kumar** [zorkow/speech-rule-engine#19]
For example : 
-5/18 is converted to minus five-eighteenths. 
But it works fine for all other types of numbers.
−15.2+48.19+(−3.698) is converted to "negative 15.2 plus 48.19 plus left-parenthesis negative 3.698 right-parenthesis"

Please let me know if you need any further information.

**Comment by zorkow** [comment]
Fixed in version 0.2.7 available via npm.
