### ISSUE TITLE
<mo> with only unicode space gets trimmed

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#201]
E.g, `<mo>&#8195;</mo>` turns into an empty `mo`.

**Comment by zorkow** [comment]
The same happens on <mo>&nbsp;</mo>. MathJax converts this into <mo>&#xA0;</mo>, which is not being removed.

**Comment by pkra** [comment]
Could you escape that?

**Comment by zorkow** [comment]
I have to admit I lost the frame reference here a bit. It's been a while, sorry.
I can not reproduce that problem (i.e., ``mo`` does not get trimmed). 
In case it should be ignored, but not trimmed, it could be related to the old-standing problem of what to do with explicit whitespace elements as in issue #9 .

**Comment by pkra** [comment]
IIRC this was about the enriched MathML turning `mo`s with whitespace into emtpy `mo`s. So it sounds like it's fixed. (I did not test if it's fixed.)
