### ISSUE TITLE
Does speech-rule-engine parse SSML input?

### ISSUE THREAD

**Issue by guest271314** [zorkow/speech-rule-engine#202]
Does speech-rule-engine parse SSML input?

**Comment by zorkow** [comment]
It primarily parses MathML input and produces speech that can contain SSML output.
But it can't parse SSML input. 
What would be a use case?

**Comment by guest271314** [comment]
> What would be a use case?

The implementation of SSML parsing at browsers, see https://github.com/guest271314/SpeechSynthesisSSMLParser
