### ISSUE TITLE
Handling of fractions with clearspeak

### ISSUE THREAD

**Issue by ryan-codingintrigue** [zorkow/speech-rule-engine#230]
I'm seeing a big difference between Mathspeak & Clearspeak in the way numbers before fractions are handled. For example:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>5</mn>
  <mfrac>
    <mn>3</mn>
    <mn>224</mn>
  </mfrac>
</math>
```

**Mathspeak**
```cmd
./bin/sre -i input.xml -d mathspeak -t default -c en
-> 5 and StartFraction 3 Over 224 EndFraction
```

**Clearspeak**
```cmd
./bin/sre -i input.xml -d clearspeak -t default -c en
-> 53224
```

Can we add a case for this? I would have expected Clearspeak's output to be (or similar to):

> 5 and 3 over 224

**Comment by zorkow** [comment]
Thanks for spotting that. I recall that I had a rule for that, but that must have vanished in cleanup.
It also turns out that the Clearspeak Grammar does not explicitly specify a rule for that case. That's maybe way I deleted it. I'll add one again.
