### ISSUE TITLE
Repeating overline syntax with Clearspeak

### ISSUE THREAD

**Issue by ryan-codingintrigue** [zorkow/speech-rule-engine#231]
I am not sure if this is expected behaviour or not, but logging here just in case. Given the following MathML:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>5.178</mn>
  <mover>
    <mn>6</mn>
    <mo accent="false">&#x00AF;<!-- ¯ --></mo>
  </mover>
</math>
```

The Mathspeak rules output:

```cmd
./bin/sre -i input.xml -d mathspeak -t default -c en
-> 5.178 ModifyingAbove 6 With bar
```

However with Clearspeak enabled, the output is this:

```cmd
./bin/sre -i input.xml -d clearspeak -t default -c en
-> the repeating decimal 5 point 1 7 8 followed by repeating digit 6
```

Is *the repeating decimal 5* supposed to be there as an indicator that there are going to be repeating digits in the number? Or should it be simply read as: *5 point 1 7 8 followed by repeating digit 6*?

**Comment by zorkow** [comment]
Hi Ryan, sorry it took me a while to get back to this.
The reading is indeed correct. Have look at the [Rules and Preferences guide](https://www.dessci.com/en/reference/ies-ets/instructional_material/ClearSpeakRulesAndPreferences.docx) page 61. The rule there states:
```the repeating decimal [number] with repeating digit [digit under bar]```

The examples however (e.g. in document `ClearSpeakExamples_Part 3_Adornments.docx`) all use
```followed by```
For example,
```The repeating decimal 2 point followed by repeating digits 1 3 4```
I have chosen to implement the latter. But in hindsight the original rule might actually make it a bit shorter.

**Comment by ryan-codingintrigue** [comment]
Perfect, thanks for clearing that up Volker!
