### ISSUE TITLE
Add support for French

### ISSUE THREAD

**Issue by dataopt** [zorkow/speech-rule-engine#233]
I can help with adding speech text for `locale=fr`.  But I am not yet sure what the work entails.

**Comment by zorkow** [comment]
I did some preliminary work, refactoring and ordering symbol mappings, in anticipation of French localisation. Unfortunately, the funding did not materialise.
However, @arnog also offered to help with French last week, so maybe we can get that done after all.
I might find a bit of time towards the end of June.

**Comment by pkra** [comment]
@zorkow according to the readme, French is supported. Is that correct/

**Comment by zorkow** [comment]
Thanks for the reminder @pkra . Indeed French language support landed in [v2.4](https://github.com/zorkow/speech-rule-engine/releases/tag/v2.4.0). Sorry I am not very good in closing old issues.
