### ISSUE TITLE
[a11y walker] WebKit SVG output fill set to "null" when moving away

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#24]
In the walker, when navigating away from a subexpression, its `rect` gets `fill="null"`, making it effectively disappear from view.

**Comment by pkra** [comment]
I still see the problem on that page using [Web 3.16.3](https://wiki.gnome.org/Apps/Web) / WebKit 2.8.5 (Ubuntu 15.10). I can double check Safari 8 later.

Have you switched the demo to SVG? (I had changed the default to CommonHTML to avoid this bug in the default state)

**Comment by pkra** [comment]
> I have found a problem with parentheses however. Where the background of the opening parenthesis is highlighted and foreground of the closing one.

What's a good example to reproduce this?

**Comment by zorkow** [comment]
Still can't reproduce the problem, but know how to fix it anyway.

Highlighting problem is, e.g., in Cauchy Schwarz: walk on the level of the parenthesis in one of the sums.

**Comment by zorkow** [comment]
PTAL.

**Comment by pkra** [comment]
The original issue has been fixed. 

I now see the parenthesis problem. On WebKit, in the CS equation, if I navigate to one of the closing paranthesis, it gets the background highlighting but its opening counterpart gets the foreground highlighting. Is that what you were seeing as well?

**Comment by pkra** [comment]
This was fixed.

**Comment by pkra** [comment]
Nope. Sorry, there was the other bug. But that's not SVG, right? New bug?

**Comment by pkra** [comment]
Closing in favor of https://github.com/zorkow/speech-rule-engine/issues/29
