### ISSUE TITLE
improving engineReady

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#247]
It would be great to have a clean way to wait for the engine to be ready, e.g., a promise.

**Comment by zorkow** [comment]
At the moment SRE is ES5 only. So no promises yet.

**Comment by pkra** [comment]
> At the moment SRE is ES5 only. So no promises yet.

A callback would do it, too, of course.

**Comment by pkra** [comment]
As per F2F, adding `mode: "sync"` to the SRE configuration seems to resolve the problem as well.

**Comment by pkra** [comment]
The mode was not as fruitful but the current beta release seems to solve this problem -- thank you, @zorkow!
