### ISSUE TITLE
Vulgar fraction with denominator 1

### ISSUE THREAD

**Issue by zorkow** [zorkow/speech-rule-engine#263]
Denominator is currently spoken as first/firsts.
Would oneth or whole be better?

**Comment by klobetime** [comment]
Wouldn't this work better by making oneth/oneths an empty string, as 2/1 is generally read as "two" rather than "two oneths"? Or does that confuse clearspeak rules like Fraction_Over?

**Comment by zorkow** [comment]
No, I strongly disagree. 
Although much of the semantic transformations SRE does are algebra-inspired and clearspeak is obviously aimed at voicing elementary algebra, we still should not actually perform arithmetic operations when interpreting an expression. 

Firstly, it's a slippery slope, where do we stop? Shall we point out that 2/0 is undefined?

Secondly, how do we even know that a fraction-like expression we see as input is indeed a fraction. What if it's a Jacobi, Legendre , or Kronecker symbol (not sure if they make sense as (a/1); not my area of expertise, but clearly omitting the 1 would be wrong)?  Unfortunately, we are not in a computer algebra system with a well-defined syntax and semantics; all we get are arbitrary formulas and we have to guess at their meaning. And unfortunately MathML (but neither LaTeX in most cases) would be powerful enough to convey the required information.

And finally, if we assume that we actually are correct with our interpretation, what does that mean for the reader: Do you give the screen reader user an advantage over one who just has the visuals? Or do you deprive persons who can't see the formula of vital information?

Sorry, a long-winded no.
But thanks for pinging the thread again, as it can be closed.
SRE seems now to produce `two oneths` and `2 over 0`.

**Comment by klobetime** [comment]
Makes sense, I (now) agree. Thanks for the consideration and response!
