### ISSUE TITLE
[a11y tool] Add role=application?

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#27]
After reading through https://github.com/w3c/aria/commit/edb65b291497a6c664d13f89f745cee2345373c2, I think changing th output's role to application when the a11y tool is loaded might be useful so that AT can automatically switch its (browse/virtual cursor etc) mode. We should discuss this with AT vendors.

**Comment by zorkow** [comment]
At least in ChromeVox this can lead to unwanted side effects. E.g., in the examples at http://progressiveaccess.com/chemistry/index.php application is pronounced multiple times.

**Comment by pkra** [comment]
Right. Maybe a11y tool needs to just announce itself in an aria live region once it's loaded?

**Comment by zorkow** [comment]
See https://github.com/mathjax/MathJax-RespEq/pull/48
