### ISSUE TITLE
Chromevox 1.31.x?

### ISSUE THREAD

**Issue by pbblair** [zorkow/speech-rule-engine#272]
I see that this is a fork of Chromevox 1.31.x, but I can't find that specific version of Chromevox distributed anywhere as a Chrome extension.  Would it be be possible, or appropriate, to mirror it here?

**Comment by pkra** [comment]
speech-rule-engine is just a part of ChromeVox, originally extracted from around 1.31 and maintained independently. 

IIRC the ChromeVox Classic (the browser extension) is not really maintained beyond security fixes; they are focused on ChromeOS nowadays.

**Comment by zorkow** [comment]
The code used to live on https://code.google.com but that does not exist anymore. 
Here's an archive on github which still contains roughly the state when I stopped maintaining SRE in ChromeVox:  https://github.com/operasoftware/chromevox
