### ISSUE TITLE
post-scripts lost with prescript and arabic base

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#273]
Apologies for the convoluted title -  couldn't narrow this down further.

Example:

```
<math><msub><none/><mn>1</mn></msub><msup><mo>&#x644;</mo><mn>2</mn></msup></math>
```

mathspeak gives me `Subscript 1 ل` (similarly for chromevox rules).

If I make the base a Latin character or remove the prescript, the result includes the superscript. (Same for other sup/subscript combinations.

**Comment by dpvc** [comment]
Have you tried replacing `<node/>` with `<mrow/>`?  I'm not sure `<none/>` is valid here.  If I'm reading the [grammar](https://w3c.github.io/mathml/appendixa-d.html#parsing.rnc.pres) correctly, `<none/>` is only allowed in `<msrow>` and `<mmultiscript>` elements.

**Comment by zorkow** [comment]
That's odd, the semantic tree is correct, i.e., it sees it as an embellished operator. It also works if you put the Arabic character into an `mi` element. Or replace it with a Greek letter, e.g.,
```XML
<math><msub><none/><mn>1</mn></msub><msup><mo>&#x1D6AA;</mo><mn>2</mn></msup></math>
```

**Comment by zorkow** [comment]
Something interferes with the embellished operators rule. This works:
```XML
<math><msup><mo>&#x644;</mo><mn>2</mn></msup></math>
```
whereas this does not:
```XML
<math><msub><none/><mn>1</mn></msub><msup><mo>+</mo><mn>2</mn></msup></math>
```
And I don't have any semantic analysis of none Greek/Latin/Hebrew characters yet. Might be a good idea just to go by alphabets.

**Comment by zorkow** [comment]
This works in the latest SRE. (But `none` does no longer work in MJ3.)
