### ISSUE TITLE
Speech should not include '-'

### ISSUE THREAD

**Issue by NSoiffer** [zorkow/speech-rule-engine#275]

**Comment by NSoiffer** [comment]
## Description
When generating speech for vulgar fractions (in at least ClearSpeak, markup='none'), the speech comes out with a  `-`. E.g, `three-fourths`.

The `-` gets spoken in screen readers at some (common?) punctuation verbosity levels. I don't think there is a good reason to use a hyphen. I think a space would work just as well and not interact poorly with screen readers.

**Comment by zorkow** [comment]
I agree. It also would make a life a lot easier.
But for some reason the ClearSpeak Rules and Preferences spec requires just that. Hence it's implemented.
Funnily enough, I just found a note to inquire about those dashes. But I guess I forgot when I was in Portland.

Anyway as chance would have it, I already have a version where I do away with most dashes to simplify unicode mappings. That should be easy to extend to numbers/fractions. And it should not take too long for it to land on master.

**Comment by zorkow** [comment]
Actually it turns out that is a genuine bug. So we must have discussed it at the time, I've changed it and it actually works in the tests. See:
http://zorkow.github.io/speech-rule-engine/resources/www/localisation/en/ClearspeakExamples.html

**Comment by zorkow** [comment]
Landed on develop.

**Comment by NSoiffer** [comment]
Thanks. Let me know if you fix the highlighting for vulgar fractions.

    Neil

**Comment by zorkow** [comment]
A proper fix might take a bit. But I have an experimental branch you might be able to play with soon.
