### ISSUE TITLE
mathspeak: leave text content alone?

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#289]
E.g., `<mtext>A simple case, e.g., here</mtext>` turns into `cap A simple case comma period e period g comma here`. This seems a bit odd and noisy for users but maybe that's intentional?

**Comment by zorkow** [comment]
That's a tricky one. Right now symbols in text is translated wrt. to a RegExp for the particular locale. That leaves words 'as is' but translates effectively all other symbols. So there is no distinction between `\alpha-> alpha`  and `, -> comma`. 

One could have a regexp for punctuation that should be ignores. But I would not quite know where to start. E.g., what about !,?, etc.

**Comment by pkra** [comment]
Do I understand correctly that this is expected behavior?
