### ISSUE TITLE
[a11y walker] implement earcons

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#30]
* Announce that the a11y tool (maybe role=application is sufficient? Can we do this only once?)
* announce edges of  levels (right, left but I'm guessing also root/leaf)

**Comment by pkra** [comment]
This might be useful http://stackoverflow.com/questions/17762763/play-wav-sound-file-encoded-in-base64-with-javascript

**Comment by zorkow** [comment]
See https://github.com/mathjax/MathJax-RespEq/pull/38

**Comment by zorkow** [comment]
> announce edges of levels (right, left but I'm guessing also root/leaf)

This is probably subsumed by announcing edges issue 26.

**Comment by pkra** [comment]
> This is probably subsumed by announcing edges issue 26.

Just wanted to make sure.

**Comment by zorkow** [comment]
Done in MathJax-RespEq PR38.
