### ISSUE TITLE
"combineContentChildren" on each node

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#318]
Via https://github.com/krautzource/mathjax-sre-walker/issues/13#issuecomment-541358936. Parsing the skeleton into a separate data structure adds some overhead and I'm wondering if it can be avoided. From what I can gather, the main problem is how to combine the children and content attributes.

From poking around the source, it seems like 

https://github.com/zorkow/speech-rule-engine/blob/cefdd11d454afae51604fdf9408fbfeaaa6e47c5/src/semantic_tree/semantic_skeleton.js#L305-L332

is where this happens for the skeleton.

Could the combined value be added as an attribute on the node?

**Comment by pkra** [comment]
Alternatively, could this be exposed in some way?

**Comment by zorkow** [comment]
So what you want is another attribute `-owns` that contains the combined `content/children` information? Is that correct?

**Comment by pkra** [comment]
> So what you want is another attribute -owns that contains the combined content/children information? Is that correct?

In the end, yes. I can also just maintain a copy of the above code (for now or long term) if that code is all there is to it.

**Comment by zorkow** [comment]
Not a good idea to maintain your own code. I had plans to eventually refactor some of this information into an improved `semantic_attributes` module. 
So I could simply add the "tree children" in their own attribute. Any particular name you'd like?
`data-semantic-owns`?

**Comment by pkra** [comment]
> So I could simply add the "tree children" in their own attribute. 

That would be great.

> Any particular name you'd like? data-semantic-owns?

I have no preference and not much knowledge of SRE's naming conventions but data-semantic-owns sounds good to me.

**Comment by zorkow** [comment]
I am just looking into this. It appears that the `-r` option does not even work. @pkra How do you run this?

**Comment by zorkow** [comment]
OK, it appears there is the short option `-r` is used twice and only `--structure` works.

**Comment by pkra** [comment]
I use a configuration object in NodeJS and set structure:true (https://github.com/krautzource/mathjax-sre-walker/blob/master/docs/source/generateDocs.js#L3-L11)

**Comment by zorkow** [comment]
Thanks. Btw., does the algorithm work as expected for matrix structures?

**Comment by pkra** [comment]
> Thanks. Btw., does the algorithm work as expected for matrix structures?

Yes, from what I've tested.

**Comment by pkra** [comment]
@zorkow in 3.0.0beta.11 (12 is not on npm btw), the root doesn't seem to get a data-semantic-owns attribute. Could this be fixed before the release of v3?

**Comment by pkra** [comment]
Quick example: 
```js
const fs = require('fs');
const sre = require('speech-rule-engine');
sre.setupEngine({
  domain: 'mathspeak',
  style: 'default',
  locale: 'en',
  speech: 'deep',
  structure: true,
  mode: 'sync'
});
sre.engineReady();
const enr = sre.toEnriched('<math><mi>2</mi><mo>+</mo><mi>2</mi></math>')
console.log(enr.toString()) // now data-semantic-owns -- <math data-semantic-type="infixop" data-semantic-role="addition" data-semantic-id="3" data-semantic-children="0,2" data-semantic-content="1" data-semantic-structure="(3 0 1 2)" data-semantic-speech="italic 2 plus italic 2"><mi data-semantic-type="number" data-semantic-role="integer" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;nemeth:number" data-semantic-id="0" data-semantic-parent="3" data-semantic-speech="italic 2">2</mi><mo data-semantic-type="operator" data-semantic-role="addition" data-semantic-id="1" data-semantic-parent="3" data-semantic-operator="infixop,+" data-semantic-speech="plus">+</mo><mi data-semantic-type="number" data-semantic-role="integer" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple" data-semantic-id="2" data-semantic-parent="3" data-semantic-speech="italic 2">2</mi></math>
```

**Comment by zorkow** [comment]
The PR should fix it.
`beta-12` is now also published. It was just meant as a quick tag for Raman, who compiles from source. But I am really trying to finalise 3. So no more betas...

**Comment by pkra** [comment]
Thanks for the fast fix, @zorkow! (I can't build it to test right now, I'm afraid.)

**Comment by pkra** [comment]
I could test now and can confirm that it's fixed.  Thanks again.

(FYI the "dynamic" way of sre4node didn't work for me when building from develop - but the CLI worked. )

**Comment by pkra** [comment]
Fixed in v3
