### ISSUE TITLE
Prosody tag attribute values

### ISSUE THREAD

**Issue by CaptLouis** [zorkow/speech-rule-engine#326]
Given this input:

`<math xmlns="http://www.w3.org/1998/Math/MathML">
    <mi>x</mi>
    <mo>=</mo>
    <mfrac>
        <mrow>
            <mo>&#x2212;
                
            </mo>
            <mi>b</mi>
            <mo>&#x00B1;
                
            </mo>
            <msqrt>
                <msup>
                    <mi>b</mi>
                    <mn>2</mn>
                </msup>
                <mo>&#x2212;
                    
                </mo>
                <mn>4</mn>
                <mi>a</mi>
                <mi>c</mi>
            </msqrt>
        </mrow>
        <mrow>
            <mn>2</mn>
            <mi>a</mi>
        </mrow>
    </mfrac>
</math>`

...I get the following output when using the _--markup_ _ssml_ option:

`<?xml version="1.0"?>
<speak version="1.1" xmlns="http://www.w3.org/2001/10/synthesis">
    <prosody rate="100%"> x
        <break time="200ms" /> equals
        <break time="450ms" />
        <prosody rate="17%"> negative b plus minus Square root of </prosody>
        <prosody rate="35%"> b <prosody pitch="17%"> squared </prosody>
            <break time="300ms" /> minus four times a times c </prosody>
        <prosody rate="17%">
            <break time="650ms" />
        </prosody> divided by <prosody rate="-18%"> two times a </prosody>
        <break time="400ms" />
    </prosody>
</speak>`

...which is really great apart from the exaggerated _prosody_ tag attribute values such as:
`rate="17%"`
`rate="35%"`
`pitch="17%"`
`rate="-18%"`

These don't sound plausible when rendered via Amazon Polly. The last example of the 4 is almost acceptable, so I wonder if the other 3 are bugged (maybe intended to be _rate="+17%"_, _rate="+35%"_ and _pitch="-17%"_ respectively). If there is a way to override the behavior, possibly using some _clearspeak_ settings, apologies for missing it in the docs.  Thanks in advance.

**Comment by zorkow** [comment]
Sorry about the delay, I've been travelling.

It appears that at some point I introduced transformation to integers, but on the constructed string, which removed the `+` sign.
PR #327 fixes the issue.

**Comment by CaptLouis** [comment]
Thank you very much, really appreciated.
