### ISSUE TITLE
3.0.0.beta.10 - standalone tool build is failing

### ISSUE THREAD

**Issue by Jayashree-ram** [zorkow/speech-rule-engine#348]
Hi

I am unable to create a standalone version of 3.0.0.beta.10 as the build is failing. I did not have this problem with beta.8. I am not sure what is amiss. Any help will be appreciated. Thanks!
*** Error ***
Building Javascript dependencies /Users/jramkumar/agilemind/zorkow_3_0_0_11/speech-rule-engine-develop/src/deps.js
Compiling Speech Rule Engine
Making interactive script.
Creating JSON destination.
Creating mappings for locale en.
head: illegal line count -- -1
make: *** [/Users/jramkumar/agilemind/zorkow_3_0_0_11/speech-rule-engine-develop/lib/mathmaps/en.js] Error 1
Jayashrees-MBP:speech-rule-engine-develop jramkumar$ make --debug
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Reading makefiles...
Updating goal targets....
 File `all' does not exist.
   File `directories' does not exist.
  Must remake target `directories'.
  Successfully remade target file `directories'.
   File `deps' does not exist.
  Must remake target `deps'.
  Successfully remade target file `deps'.
   File `compile' does not exist.
  Must remake target `compile'.
  Successfully remade target file `compile'.
   File `start_files' does not exist.
  Must remake target `start_files'.
  Successfully remade target file `start_files'.
   File `maps' does not exist.
     File `/Users/jramkumar/agilemind/zorkow_3_0_0_11/speech-rule-engine-develop/lib/mathmaps/es.js' does not exist.
    Must remake target `/Users/jramkumar/agilemind/zorkow_3_0_0_11/speech-rule-engine-develop/lib/mathmaps/es.js'.
Creating mappings for locale es.
head: illegal line count -- -1
make: *** [/Users/jramkumar/agilemind/zorkow_3_0_0_11/speech-rule-engine-develop/lib/mathmaps/es.js] Error 1

**Comment by zorkow** [comment]
Thanks for reporting this. The way the `mathmaps` are treated has changed considerably from `3.0.0-beta.9` to `3.0.0-beta.10`. They are no longer loaded from source but always need to be built, even locally. 

What you see, seems to be an OSX problem, I was not aware of. 
I just found [this on stackexchange](https://unix.stackexchange.com/questions/169079/negative-arguments-to-head-tail)

I'll look into it.

**Comment by zorkow** [comment]
That problem should be fixed now. Could you test with `v3.0.0-beta.12` and confirm?

**Comment by Jayashree-ram** [comment]
Yes, it is fixed now. Thank you very much!
