### ISSUE TITLE
Is it possible to use toJson(mathml) in browser?

### ISSUE THREAD

**Issue by xZGit** [zorkow/speech-rule-engine#353]

**Comment by zorkow** [comment]
Yes, it is. 
As an example, where it is used, have a look at the [semantic tree visualiser](http://zorkow.github.io/semantic-tree-visualiser/visualise.html). When you tick the `Show Json` box you get the JSON output at the bottom of the page.

**Comment by xZGit** [comment]
yes., I try it and it is successful. But you write "This method only works in Node, not in browser mode."  in README.MD

Method | Return Value |
----|----
toJson(mathml) | The semantic tree in JSON. This method only works in Node, not in browser mode.



so I have a little confuse why you say that.

Anyway, this package helps me a lot. Thank you!

**Comment by zorkow** [comment]
Thanks for pointing that out. I am in the process of rewriting the README anyway. So this should go.
