### ISSUE TITLE
Extra Nemeth characters in simple definite integral

### ISSUE THREAD

**Issue by rbeezer** [zorkow/speech-rule-engine#394]
Quite careful testing gives the following:

```latex
\begin{gather*}
\int_a^b f(x) dx
\end{gather*}
```

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable displaystyle="true" columnspacing="1em" rowspacing="3pt">
    <mtr>
      <mtd>
        <msubsup>
          <mo data-mjx-texclass="OP">∫</mo>
          <mi>a</mi>
          <mi>b</mi>
        </msubsup>
        <mi>f</mi>
        <mo stretchy="false">(</mo>
        <mi>x</mi>
        <mo stretchy="false">)</mo>
        <mi>d</mi>
        <mi>x</mi>
      </mtd>
    </mtr>
  </mtable>
</math>
```

SRE Nemeth
```
⠮⠰⠁⠘⠃⠐⠋⠷⠭⠾⠙⠠⠀⠭
```

ASCII Braille
```
!;a~b"f(x)d, x 
```

The comma-space (dot-6, space) seems additional.

**Comment by zorkow** [comment]
I can't reproduce that. Even in older versions of SRE. For the given expression I get:
```
⠮⠰⠁⠘⠃⠐⠋⠷⠭⠾⠙⠭
```
Now there is an invisible comma between `d` and `x`.  On exploration you can see that as
```
⠠⠀
```
but not for the entire expression. How are you translating this?

**Comment by rbeezer** [comment]
Thanks, Volker.  Yes, I get the same/correct result when I use the SRE (beta5) executable at the command line.  It seems it is our (renamed) script @dpvc put together

https://github.com/rbeezer/mathbook/blob/dev/script/mjsre/mj-sre-page.js

which is a black-box to me - I can't tell where/how to investigate further.

```bash
$ node mj-sre-page.js --braille sre-394.html
```

produces

```
⠮⠰⠁⠘⠃⠐⠋⠷⠭⠾⠙⠠⠀⠭
```

Pasting input file, since I can't upload it.  I don't think the `gather` is necessary to duplicate the problem.

```html
<html>
<body>

<p>
\begin{gather*}
\int_a^b f(x) dx
\end{gather*}
</p>

</body>
</html>
```

**Comment by rbeezer** [comment]
Thanks for the fix at:  https://github.com/rbeezer/mathbook/pull/1351
