### ISSUE TITLE
Products are listed as sums

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#4]
I'm not sure if this is as intended or not, but the TeX code `\prod_{n=1}^{10} n` produces

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <munderover>
    <mo>&#x220F;<!-- ∏ --></mo>
    <mrow class="MJX-TeXAtom-ORD">
      <mi>n</mi>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <mrow class="MJX-TeXAtom-ORD">
      <mn>10</mn>
    </mrow>
  </munderover>
  <mi>n</mi>
</math>
```

which is enhanced as

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" type="bigop" role="sum" id="8" children="6,7">
  <munderover type="limboth" role="sum" id="6" children="0,4," parent="8">
    <mo type="largeop" role="sum" id="0" parent="6">&#x220F;</mo>
    <mrow class="MJX-TeXAtom-ORD" type="relseq" role="equality" id="4" children="1,3" content="2" parent="6">
      <mi type="identifier" role="latinletter" id="1" parent="4">n</mi>
      <mo type="relation" role="equality" id="2" operator="relseq,=" parent="4">=</mo>
      <mn type="number" role="integer" id="3" parent="4">1</mn>
    </mrow>
    <mrow class="MJX-TeXAtom-ORD" parent="6">
      <mn type="number" role="integer" id="5" children="">10</mn>
    </mrow>
  </munderover>
  <mi type="identifier" role="latinletter" id="7" parent="8">n</mi>
</math>
```

Here the structure is right, but the `role="sum"` seems counter-intuitive on the elements with id's 8, 6, and 0.

**Comment by zorkow** [comment]
Sums is a generic semantic category that comprises all the "sum like" big operators:
 '⅀',        '∏', '∐', '∑', '⋀', '⋁', '⋂', '⋃', '⨀', '⨁', '⨂', '⨃', '⨄', '⨅',   '⨆', '⨇', '⨈', '⨉', '⨊', '⨋', '⫼'

For screen reader purposes this would suffice, i.e. rendering
>name of unicode character< from >lower bound< to  >upper bound<

Otherwise we would need a separate category for all of them.

**Comment by dpvc** [comment]
OK, I thought that might be the case.

Is it possible to add a pointer on the `bigop` element that points to the actual largeop (even though that is farther down in the tree)?  Otherwise, I have to look for it by hand, when you probably know where it is already.

**Comment by zorkow** [comment]
bigop has exactly two children: operator, operands
[Some of the this is in the (incomplete) grammar document. Let me push a new version.]

But I see what you mean with a direct pointer to the largeop element. I could put the large operator into the content (similar to what we have on infixop). That should not break anything (maybe a few tests...)

**Comment by zorkow** [comment]
There's also still something wrong with the children being added. The lim both node has three 0,4,5.
 I've fixed that yesterday. I'll let you know when I have merged that branch.

**Comment by dpvc** [comment]
Yes, listing it in the content would be great.  The point is, if I need to use the actual operator to tell what the semantics really are, then I would like to be able to get to it from the bigop element directly.  For example, if the sum doesn't have limits (e.g., `\sum a_n` rather than `\sum_{n=1}^\infty a_n`), then I have to test the first child to see if it is just the `<mo>` itself rather than a `<msubsup>`, `<msub>`, or `<msup>`.  That certainly can be done, but it is extra logic that it would be nice to avoid.

**Comment by zorkow** [comment]
Do we need something similar for integrals or function applications? Example for the latter is:
sin^2 (x) gives us a function application of the sin^2. We could point straight to the sin.

**Comment by dpvc** [comment]
That might be good if it is not too hard to add.

**Comment by zorkow** [comment]
This works now. Content node with pointer to largeop. Works also for integrals and functions.

**Comment by dpvc** [comment]
I'm not seeing this (or not looking in the right place).  Can you give an example of how it works now?

**Comment by zorkow** [comment]
For the initial example, you should now get the following output:

```html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" type="bigop" role="sum" id="8" children="6,7" content="0">
  <munderover type="limboth" role="sum" id="6" children="0,4,5" parent="8">
    <mo type="largeop" role="sum" id="0" parent="8" operator="bigop">∏<!-- ∏ -->
    </mo>
    <mrow class="MJX-TeXAtom-ORD" type="relseq" role="equality" id="4" children="1,3" content="2" parent="6">
      <mi type="identifier" role="latinletter" id="1" parent="4">n</mi>
      <mo type="relation" role="equality" id="2" parent="4" operator="relseq,=">=</mo>
      <mn type="number" role="integer" id="3" parent="4">1</mn>
    </mrow>
    <mrow class="MJX-TeXAtom-ORD">
      <mn type="number" role="integer" id="5" parent="6">10</mn>
    </mrow>
  </munderover>
  <mi type="identifier" role="latinletter" id="7" parent="8">n</mi>
</math>

```

The outer most element is of bigop type. It has two children, the big operator (in our case the product and its limits) and the argument. It also now has a content element, which points directly to the large operator. In our case the product sign. So if you follow that link, you know what you have. 
It should also work for integrals, functions like sin, cos and simple functions like f(x), f'(x), f^2(x). In the latter case it points to the f.

**Comment by zorkow** [comment]
I've put some more example into the Wiki at:
https://github.com/mathjax/MathJax/wiki/Big-Operator-and-Function-Examples

**Comment by dpvc** [comment]
Thanks, now I see it.  I was looking for the wrong thing.
