### ISSUE TITLE
Number signs in Nemeth

### ISSUE THREAD

**Issue by rbeezer** [zorkow/speech-rule-engine#403]
(I've got a list of issues from a transcriber and am doing my best to identify what is best to report to SRE.  Feel free to close liberally.  Numbers are from her list, so she and I can stay organized.)

> 2.  We don't need the number sign if it follows a mathematical symbol.

**Comment by zorkow** [comment]
Can you give me the exact expression?
I am a bit confused about the categorical answer: The rules in Nemeth 72, \S 9-11, contain quite a number of rules where the number indicator has to be used after a preceding mathematical symbol. 
I thought SRE implements those rules quite faithfully now, but there might still be the occasional bug.

**Comment by zorkow** [comment]
3.2.0-beta.3 contains yet another overhaul of the number indicator, which conforms to all the rules I've seen so far.
While there can still be bugs, I am closing this for more specific issues, if we find some.
