### ISSUE TITLE
Superscript of superscript

### ISSUE THREAD

**Issue by rbeezer** [zorkow/speech-rule-engine#404]
\\(e^{-x^2}\\)

Transcriber says:

> 7. Superscripts with a superscript are showing up in braille with an extra (4,5) 
> dots before going back to baseline.  You don't need to "step down" when going 
> from a superscript with a superscript.  Sometimes the dot 5 is all that is 
> missing.  You can just return to baseline with a dot 5.  I am deleting the extra 
> (4,5).

**Comment by zorkow** [comment]
I either misinterpret what the transcriber said, or it is not in line with UEB book 8.6, or the issue has resolved itself already. 
Either way, I don't think that branch `issue_404` is the right solution.

Currently `e^{-x^2}` translates to
```
⠑⠘⠤⠭⠘⠘⠆
```

**Comment by zorkow** [comment]
Correct in its current state.
