### ISSUE TITLE
Equality in an integral's limits

### ISSUE THREAD

**Issue by rbeezer** [zorkow/speech-rule-engine#405]
\\(\int_{x=2}^{x=5} x^3 dx\\)

> 12. There is a space after the x and before the equal.  The subscript or superscript 
> needs to be reestablished by adding the (4,5) or (5,6).  It doesn't have to be 
> included before the answer.  But then a dot 5 needs to be added before moving on 
> to establish baseline.

**Comment by zorkow** [comment]
Solved in PR #510 .
