### ISSUE TITLE
IE 11 gives different results to chrome

### ISSUE THREAD

**Issue by kevinMarshallTexthelp** [zorkow/speech-rule-engine#41]
**MathML**
```
<math   xmlns="http://www.w3.org/1998/Math/MathML">
          <mstyle>
            <mi>f</mi>
            <mrow>
              <mo>(</mo>
              <mi>a</mi>
              <mo>)</mo>
            </mrow>
            <mo>=</mo>
            <mfrac>
              <mn>1</mn>
              <mrow>
                <mn>2</mn>
                <mi>π
                  <!-- π -->
                </mi>
                <mi>i</mi>
              </mrow>
            </mfrac>
            <msub>
              <mo>∮</mo>
              <mrow>
                <mi>γ</mi>
              </mrow>
            </msub>
            <mfrac>
              <mrow>
                <mi>f</mi>
                <mo>(</mo>
                <mi>z</mi>
                <mo>)</mo>
              </mrow>
              <mrow>
                <mi>z</mi>
                <mo>−</mo>
                <mi>a</mi>
              </mrow>
            </mfrac>
            <mi>d</mi>
            <mi>z</mi>
          </mstyle>
        </math>
```
**IE 11**
f ( a ) = 12 π i ∮ γ f ( z ) z − ADZ
**Chrome**
f left parenthesis a right parenthesis equals start fraction one over two pi i end fraction contour integral sub gamma start fraction f left parenthesis z right parenthesis over z minus a end fraction d z

**Comment by zorkow** [comment]
Thanks for the feedback.
Could you give me some details, on which version and how you are using sre? I.e., is it the latest via npm or something compiled directly from the github repo and if so, which target have you compiled?

Taking a guess on what the problem could be: IE has no xpath implementation (the one in Edge is incomplete) and sre relies on that. Therefore in the version we currently use with MathJax, I include [wgxpath](https://github.com/google/wicked-good-xpath). However, that is not exposed via npm yet.

Could you please test you expression [here](https://mathjax.github.io/MathJax-RespEq/Semantics-Lab/MathML.html) and check the result in the first speech attribute in the enriched MathML expression below, whether this gives you the expected speech string on IE11.

**Comment by kevinMarshallTexthelp** [comment]
I have compiled pull#37 from https://github.com/zorkow/speech-rule-engine.git and i have included wgxpath. 

The output from IE is "f left-parenthesis a right-parenthesis equals StartFraction 1 Over 2 pi i EndFraction contour-integral Underscript gamma Endscripts StartFraction f left-parenthesis z right-parenthesis Over z minus a EndFraction d z" 

The only think I did notice was when i do a build I get sre_browser and you are using sre_mathjax on the page. Could this be the issue?

**Comment by zorkow** [comment]
> The only think I did notice was when i do a build I get sre_browser and you are using sre_mathjax on 
> the page. Could this be the issue?

That is indeed the issue. The browser goal is from a time before we started experimenting with MathJax in IE/Edge. 
However, I have been revamping the API anyway --- currently in the develop branch --- and wanted go over the goals in the Makefile before merging with master. Hopefully that will be ready by the end of the week. I'll close the issue once this is done.

**Comment by kevinMarshallTexthelp** [comment]
Thanks For the help

**Comment by zorkow** [comment]
I have just merged develop into master. sre_browser now correctly loads wgxpath (tested with Win 7, IE11).
