### ISSUE TITLE
href affordances

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#413]
While links don't cause any direct issues, they are not discoverable. I.e., speech and braille outputs do not indicate the presence of a link (either on the top level or when exploring).

**Comment by pkra** [comment]
Also, in the walker, links cannot be activated. Not sure in how far that's more a MathJax issue.

**Comment by pkra** [comment]
Coming back to this, it seems difficult to patch in post-processing. It might help if SRE could separate out the href to its own wrapper.

**Comment by pkra** [comment]
@zorkow following up on our conversation, I've been wondering if instead of pushing the link to the first semantic child I could make all semantic children links down the line - I'm just not sure what markup to expect. Could you remind me of the example you gave where a link would have multiple children instead of a single wrapper?

**Comment by zorkow** [comment]
These are no being pushed through in SRE and announced as suffixes. On the basis of this we should probably also be able to make them work during exploration in MathJax.
A few remarks:
* Links will not be broken up by rewriting groups, e.g., in the juxtaposition heuristic. I.e.,  the `bc` in
```LaTeX
{{xyz}{a\href{https://foo}{bc}}}
```
will remain a single node and therefore a reachable link.

* Rewriting in fenced expressions can alter the nature of links:
```LaTeX
(x+y\href{https://foo}{)^2}
```
will lead to the entire parenthesised expression becoming a link.

```
(\href{https://bar}{x+y}\href{https://foo}{)^2}
```
will result in `(  )^2` linking to foo, while `x+y` will link to bar.

**Comment by pkra** [comment]
Ah, dang, I actually changed my mind on this (and #414). Or rather: I understand that adding suffixes make sense from a MatHjax point of view, i.e., when using live regions. However, I rely on "regular" element semantics, i.e., I can leave suffixes to AT. 

I need to take a look at the implementation but I guess I now need to remove the suffixes; will let you know how that goes.
