### ISSUE TITLE
surfacing mlgyph 

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#414]
For regular images / role=img, users are accustomed to AT surfacing the structure of the content, e.g., speech will get a suffix of "image" or "graphic". While this might be noisy, it does clarify what a user can expect to get from the content (e.g., when copy&pasting).

It could be helpful if SRE could surface something similar, e.g., when exploration hits the mglyph leaf.

**Comment by zorkow** [comment]
We can now announce `image`. Suffixes will be accumulated, i.e., if the glyph is a link `image link` will be announced.
