### ISSUE TITLE
Odd Braille output when setting domain

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#416]
This is a random (read: ignorable) find while figuring out the APIs -- this might just be "correct"/working as intended.

The following sample came out of modifying an existing speech config for braille output:

```
const sre = require('speech-rule-engine');
sre.setupEngine({
  locale: 'nemeth',
  domain: 'clearspeak',
  modality: 'braille',
});
sre.engineReady();

const enriched = sre.toSpeech('<math><msup><mi>x</mi><mn>2</mn></msup></math>');
console.log(enriched.toString()); // "⠭squared"
```

Removing the domain works fine ("⠭⠘⠆").

**Comment by zorkow** [comment]
Classic GIGO case... But this should no longer happen, as SRE will switch back to default in modality `braille`. However, you can still get that behaviour if you use `modality: speech` with `nemeth`.

**Comment by zorkow** [comment]
PS: Don't use top-level `const`, `let` outside module or import/export context. It is particularly annoying in test code you might want to copy multiple times into the same node REPL.
