### ISSUE TITLE
skeleton problem in msubsup

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#418]
E.g., starting with TeX `A^2_ <`, I end up seeing something like  

`data-semantic-children="0,1,2" data-semantic-collapsed="(4 (3 0 1) 2)" data-semantic-owns="3 2"`

The semantic-children seem ok but the semantic-owns should match it (and the 3 does not match anything in the eventual output, thus causing an error).

**Comment by zorkow** [comment]
PR #419 should solve that problem. Please have a look and let me know if that works for you. 
If it does, I have an idea how to considerably simplify the current computations.

Other "collapse heavy" examples I have in my tests are:

```html
<mrow><msubsup><msubsup><mi>sin</mi><mn>2</mn><mn>1</mn></msubsup><mi>n</mi><mi>m</mi></msubsup><mi>x</mi></mrow>
```

```html
<mi>a</mi><mtext>to</mtext><mi>b</mi><mtext>to</mtext><mi>c</mi>
```

```html
<mrow><mi>a</mi><mo>+</mo><mi>b</mi><mtext>is not the same as</mtext><mi>a</mi><mi>b</mi><mtext>in general.</mtext></mrow>
```

```html
<mmultiscripts><mi>X</mi><mi>i</mi><none/><none/><mi>l</mi></mmultiscripts>
```

```html
<mmultiscripts><mi>A</mi><mn>3</mn><mn>4</mn><mi>k</mi><mi>l</mi><mprescripts/><mn>1</mn><mn>2</mn><mi>i</mi><mi>j</mi></mmultiscripts>
```

```html
<mmultiscripts><mi>A</mi><mn>1</mn><mn>2</mn><mn>3</mn><mprescripts/><mn>5</mn><mn>4</mn><mn>6</mn></mmultiscripts>
```

**Comment by pkra** [comment]
Thanks, Volker. It fixes the example in the OP. I'll try to check more examples tomorrow.

**Comment by pkra** [comment]
> Thanks, Volker. It fixes the example in the OP. I'll try to check more examples tomorrow.

Not quite tomorrow but I tested the other examples where I had (similar) issues and I no longer see any issues. Thanks again!

**Comment by pkra** [comment]
I believe this can be closed (at least the PR is merged).

**Comment by pkra** [comment]
> I believe this can be closed (at least the PR is merged).

Fool that I was, I ran into it again in #448. Could we have a release?
