### ISSUE TITLE
menclose updiagonalstrike tag is ignored

### ISSUE THREAD

**Issue by klobetime** [zorkow/speech-rule-engine#435]
The generated text does accurately reflect the given equation, but the crossed-out terms aren't indicated so the text doesn't reflect the entire visual. Probably related to #361.

Generated (clearspeak) text: _the fraction with numerator 60 mi and denominator hr times 5280 feet over 1 mi times 1 hr over 60 minutes equals 5280 feet over minutes_

Generated (mathspeak) text: _60 times mi divided by hr times 5280 feet divided by one times mi times one times hr divided by 60 minutes equals 5280 feet divided by minutes_

```html
<math>
    <mrow>
        <mfrac>
            <mrow>
                <mn>60</mn>
                <menclose notation="updiagonalstrike">
                    <mi class="MathML-Unit" mathvariant="normal">mi</mi>
                </menclose>
            </mrow>
            <menclose notation="updiagonalstrike">
                <mi class="MathML-Unit" mathvariant="normal">hr</mi>
            </menclose>
        </mfrac>
        <mo>×</mo>
        <mfrac>
            <mrow>
                <mn>5280</mn>
                <mi class="MathML-Unit" mathvariant="normal">ft</mi>
            </mrow>
            <mrow>
                <mn>1</mn>
                <menclose notation="updiagonalstrike">
                    <mi class="MathML-Unit" mathvariant="normal">mi</mi>
                </menclose>
            </mrow>
        </mfrac>
        <mo>×</mo>
        <mfrac>
            <mrow>
                <mn>1</mn>
                <menclose notation="updiagonalstrike">
                    <mi class="MathML-Unit" mathvariant="normal">hr</mi>
                </menclose>
            </mrow>
            <mrow>
                <mn>60</mn>
                <mi class="MathML-Unit" mathvariant="normal">min</mi>
            </mrow>
        </mfrac>
        <mo>=</mo>
        <mfrac>
            <mrow>
                <mn>5280</mn>
                <mi class="MathML-Unit" mathvariant="normal">ft</mi>
            </mrow>
            <mi class="MathML-Unit" mathvariant="normal">min</mi>
        </mfrac>
    </mrow>
</math>
```

**Comment by zorkow** [comment]
It is indeed related to issue #361. I am currently in the process of analysing and collating the speech rule sets. That should remove redundancy as well as fill gaps. This will in particular also fix the missing rules in clearspeak for enclosed and tensor elements. 
Watch branch `speech_rule_analysis`. That will hopefully land in the next release.

**Comment by zorkow** [comment]
Adds new Clearspeak rules for enclosed elements including a specialised preference.
Currently for English only, but needs to be extended once the speech rule system is revamped.
