### ISSUE TITLE
visulizer broken in Firefox?

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#437]
I'm no longer able to get the visualizer to work in FF - always get an alert with "Something went wrong on rerendering." and MathJax retry errors in the console. (FWIW Chrome is fine.)

**Comment by zorkow** [comment]
Are you using this version: http://zorkow.github.io/semantic-tree-visualiser/visualise.html

In case you are using the `index.html` version at that location, that would fail as it loads libraries, locally i.e., from `node_modules`.

**Comment by pkra** [comment]
> Are you using this version: http://zorkow.github.io/semantic-tree-visualiser/visualise.html

Yes. Well, actually no. I was on https (linked from the readme). 

Using http works, but https doesn't seem to.

**Comment by zorkow** [comment]
Still, works fine for me with `https` and with FF 82.0.2.  Is that the latest version?

**Comment by pkra** [comment]
> Still, works fine for me with `https` and with FF 82.0.2. Is that the latest version?

Weird. I'm on the same version (and OS I presume). Not sure what's broken on my end then.

Sorry for the noise.

**Comment by zorkow** [comment]
Just for completeness: Works for FF82.0.2 in Mint and FF82.0.3 in Win 10.
For what it's worth, I get the problem with the `keep` button. But that's always been a bit flakey.
