### ISSUE TITLE
Division signs read literally with clearspeak

### ISSUE THREAD

**Issue by klobetime** [zorkow/speech-rule-engine#442]
With ClearSpeak, the following expression generates "9 division sign 3 is not equal to 9 times 3" when I'd expect "9 divided by 3 is not equal to 9 times 3" instead.  Rendering is as expected.

```xml
<math>
    <mn>9</mn>
    <mo>&divide;</mo>
    <mn>3</mn>
    <mo>&ne;</mo>
    <mn>9</mn>
    <mo>&times;</mo>
    <mn>3</mn>
</math>
```

**Comment by zorkow** [comment]
This is related to issue #376 and PR #377. 
PR #442 fixes this problem for English.

**Comment by zorkow** [comment]
This rule is now available in all locales.
