### ISSUE TITLE
Are data-semantic-owns nodes always descendants? 

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#446]
I couldn't produce a case where semantic children are not descendants. Is that generally the case?

**Comment by zorkow** [comment]
When you say descendants, do you mean descendants in the mml tree? In that case, no. There are a couple of heuristics pull elements together from different branches of the syntactic tree. 
At least one will be in the upcoming release for `lim` and `script` types. I'll try to find an example.

**Comment by pkra** [comment]
> When you say descendants, do you mean descendants in the mml tree? 

Yes.

> In that case, no. There are a couple of heuristics pull elements together from different branches of the syntactic tree.
> At least one will be in the upcoming release for `lim` and `script` types. I'll try to find an example.

Thanks, I suspected as much. An example would be great (for writing  test(.

**Comment by pkra** [comment]
A example (downstream) are labeled table rows in MathJax output being torn out of their rows.
