### ISSUE TITLE
Nemeth start/endLabel not given as braille patterns 

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#447]
Something like `\begin{equation} x\tag{1}\end{equation}` gives `with Label⠷⠂⠾EndLabel⠭`. 

Could these come out as pure braille pattern strings?

**Comment by pkra** [comment]
@zorkow any news on this after the recent Nemeth updates? For aria-braillelabel, the spec says it must be either "all dot patterns" or "no dot patterns".

**Comment by zorkow** [comment]
The last beta fixed that.
