### ISSUE TITLE
installing branch via npm

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#450]
Would it be possible to get  `$ npm i github:zorkow/speech-rule-engine` to provide a version that can be built?

**Comment by zorkow** [comment]
Possibly. Do you know what scripts are being run during that installation and if it pulls dev dependencies?

**Comment by pkra** [comment]
>  Do you know what scripts are being run during that installation

No.

> and if it pulls dev dependencies?

No but I wouldn't expect it too. 

I would expect to have to do my own positinstall script to run npm i in the node_modules folder and then make. 

However, there's no makefile when installing it this way. I have no idea why and it seems neither do you. I'll just clone it manually for now..
