### ISSUE TITLE
German locale (sometimes) producing "equals"

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#478]
Something like "a^2 + b^2 = c^2" gave me "a Quadrat plus b Quadrat equals c Quadrat".

**Comment by pkra** [comment]
Sorry for the poor report. It's a MathJax 3.1.2 issue and it might be a caching issue.

* Go to https://www.mathjax.org/#demo
* enter $a^2 + b^2 = c^2$ in the demo
* activate walker on expression (to get English "a squared plus b squared equals c squared")
* switch locale to German
* activate walker on expression => get "a Quadrat plus b Quadrat equals c Quadrat"

If I switch the locale straight away, I get a correct result.

**Comment by zorkow** [comment]
That is a known problem as some of the menu commands do not trigger a rerender (thus deleting already computed speech attribute). When you hit the render button, it works.
Follow ups to [PR 561](https://github.com/mathjax/MathJax-src/pull/561) will work on that.
