### ISSUE TITLE
3.2.0-beta3 regression: new juxtaposition problem

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#486]
Somewhat reduced test case: 

`\begin{align}  - &{\Delta x} \frac{\beta }{2}\sum _i (a_i^{n,+}+c^n)\rho _i^{n,+}\left(|x_{i+{1/2}}|-|x_{i-{1/2}}| \right) \tag{3.15}\end{align}`

The beta/2 is moved to the end of the row.

With beta2:

![image](https://user-images.githubusercontent.com/426686/113040741-72624a00-9199-11eb-8d46-5e6e98aa0a8b.png)

with beta3: 

![image](https://user-images.githubusercontent.com/426686/113040763-79895800-9199-11eb-8b3e-f4f2504c10ef.png)

**Comment by pkra** [comment]
I have more test cases like this if that's helpful.

**Comment by zorkow** [comment]
Thanks. Here's a minimal example.

```latex
\begin{align} {\Delta x}\beta\sum a\end{align}
```

**Comment by zorkow** [comment]
> I have more test cases like this if that's helpful.

Can you just send me a JSON structure in [this format](https://speech-rule-engine.github.io/sre-tests/#generating-tests)?

**Comment by pkra** [comment]
> Can you just send me a JSON structure in [this format](https://speech-rule-engine.github.io/sre-tests/#generating-tests)?

Not sure I understand that documentation page. Just an object with a single key for this issue and array with cases?

**Comment by pkra** [comment]
This seems fixed in beta4 (alongside the other test cases I had sent you by email). I did spot some semantic-owns related errors that I'll need to investigate (i.e., where my sre2tree fails later on); I don't know if I missed them earlier.
