### ISSUE TITLE
crashes / hangs on certain expressions

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#488]
This might be related to #487. With the setup mentioned there, the following crash on 3.1 (Node.insertBefore: The new child is an ancestor of the parent) and hang on 3.2-beta

* `\begin{align*} &\left<F(z)-c\otimes 1,F(z)-c\otimes 1\right> \\ =& \left<F(z),F(z)\right>-2\left<c\otimes 1,F(z)\right>+||c||^2\\ =& 1 -2\left( c_3\sin (z)+c_4\cos (z) \right) +||c||^2 \end{align*} `
* `\begin{align*} &\left\lt F(z)-c\otimes 1,F(z)-c\otimes 1\right\gt  \\ =& \left\lt F(z),F(z)\right\gt -2\left\lt c\otimes 1,F(z)\right\gt +||c||^2\\ =& 1 -2\left( c_3\sin (z)+c_4\cos (z) \right) +||c||^2 \end{align*} `
* `\begin{eqnarray*} \nabla \|x\| &=& \frac{x^{\top }}{\| x \|},\\ \| \nabla \| x \| \|^2 &=& \frac{\| x^{\top } \|^2 }{\|x\|^2 } \leq 1 , \\ \triangle \| x\| &=& \frac{1}{\|x\|} \left( \frac{1}{2} \triangle \| x\|^2 - \| \nabla \|x\| \|^2 \right) = \frac{1}{\|x\|} \left( \langle x , \overrightarrow {H} \rangle + n - \| \nabla \|x\| \|^2 \right). \end{eqnarray*} `

**Comment by zorkow** [comment]
This is related to 
A fences issue. 
1. Seems to be an old issue.
```latex
||c||^2\
```
2. Related to allowing parallel as fence
```latex
\| \nabla \|x\| \|^2
```

**Comment by zorkow** [comment]
Absolute minimal example:
```latex
x\| \|^2
```
