### ISSUE TITLE
Behavior change in speech-rule-engine 3.2.0?

### ISSUE THREAD

**Issue by agileminddev** [zorkow/speech-rule-engine#515]
When trying to upgrade from v3.1.1 to v3.2.0 I'm seeing tests fail for reasons I don't understand.

I created a simple two file project that illustrates the issue:
## package.json ##
```json
{
  "name": "failure-example",
  "license": "UNLICENSED",
  "private": true,
  "engines": {
    "node": "14.15.5",
    "npm": "6.14.11"
  },
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "speech-rule-engine": "3.2.0"
  },
  "devDependencies": {
    "jest": "^26.6.3"
  },
  "jest": {
    "notify": false,
    "silent": true,
    "verbose": true
  }
}
```

## example.test.js ##
```javascript
const sre = require('speech-rule-engine');

beforeAll(() => {
    sre.setupEngine({
        domain: 'mathspeak'
    });
});

test('simple single math', () => {
    expect(JSON.parse(JSON.stringify(sre.engineSetup(), ['domain', 'locale', 'speech', 'style'])))
        .toEqual({
            locale: 'en',
            speech: 'none',
            style: 'default',
            domain: 'mathspeak',
        });
    expect(sre.engineReady())
        .toBeTruthy();
    expect(sre.toSpeech('<math><mrow><msup><mn>3</mn><mn>7</mn></msup></mrow></math>'))
        .toBe('3 Superscript 7');
});
```

Running `npm install` and `npm run test` results in a failure because SRE is returning *37* instead of *3 Superscript 7*. Editing package.json to use v3.1.1 of the engine and rerunning results in a passing test.

Obviously something has changed, but I'm totally missing what I need to do to adapt. Has anyone else encountered this, or see what I clearly do not?

**Comment by zorkow** [comment]
The change that might have caused this is the new dynamic loading of speech rules. They are now bundled with the mappings for Unicode characters. The results looks like SRE can't find the rule for superscript in MathSpeak, teh v3.1.1 files won't contain those.

Can you check that you are using the correct locale files in the mathmaps directory? `lib/mathmaps/en.js` should contain entries of the form `en/rules/`, e.g., `en/rules/mathspeak_english.js`.

**Comment by zorkow** [comment]
I had a quick look. The problem is that not 3.2.0, but that jest does not wait for sre to be ready. 
The test was only correct by a fluke in 3.1.1 as the rules were compiled into the core. The following test fails with the above setup in 3.1.1 as well as the locale is not loaded:

```
expect(sre.toSpeech('<math><mo>=</mo></math>'))
        .toBe('equals');
```

```
    Expected: "equals"
    Received: "="
```

The main reason is that jest fails to load the locale file. Setting `"silent": false` will show the error: 

```
 Unable to load file: /tmp/tests/node_modules/speech-rule-engine/lib/mathmaps/en.js
      TypeError: Cannot read property 'readFileSync' of null
```

The reason for this error is that jest does not know that it runs in node. If you add 
```
    "testEnvironment": "node",
```
to you jest configuration in the `package.json` it should work fine.

**Comment by agileminddev** [comment]
Aha -- thank you so much!  Because the setup worked consistently with the 3.1.1 release it didn't occur to me that the issue wasn't in the one element that changed.  I truly appreciate your help!
