### ISSUE TITLE
[v4.0.0-alpha.1] dropped spaces in speech

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#522]
With 

```js
sre.setupEngine({
    domain: 'mathspeak',
    style: 'default',
    locale: 'fr',
    speech: 'deep',
    structure: true,
    mode: 'sync',
  });
sre.engineReady();
sre.toEnriched(mml).toString()
```
E.g., something like `x = y` gives me `xégaley` (no spaces) on the top level data-semantic-speech attribute.

**Comment by pkra** [comment]
Renamed since this is not about localization after all.

e.g., `I\subseteq \mathcal{O}_X` gives me `upper Isubset of or equal toscriptupper OSubscriptupper X`

**Comment by zorkow** [comment]
I can't reproduce the problem. Could it be that you ran SRE with braille before?
Could you try and add `modality: 'speech'` to your setup vector and see if that solves the problem?

**Comment by pkra** [comment]
> Could it be that you ran SRE with braille before?

Yes.

>  Could you try and add modality: 'speech' to your setup vector and see if that solves the problem?

Yes and this seems to resolve the issue (at least the first one which I can test quickly). Now I need to track down those weird visual changes I get with v4...

**Comment by zorkow** [comment]
Should resolve both issues as the problem is the incorrect separator. The spaces you see in the second speech output stem from translations of unicode characters  (alphabets are automatically generated).

In an ideal world you should not get any visual changes. All tests pass.

**Comment by pkra** [comment]
> In an ideal world you should not get any visual changes. All tests pass.

After setting the modality to speech, I'm not seeing any changes in the output. That's pretty damn awesome.
