### ISSUE TITLE
bug: cannot install speech-rule-engine@3.3.2

### ISSUE THREAD

**Issue by PeachScript** [zorkow/speech-rule-engine#527]
## Versions
- Node.js: 15.6.0
- NPM: 7.4.0
- speech-rule-engine: 3.3.2

## Steps to reproduce
Simply execute `npm i speech-rule-engine@3.3.2`, we will get the following error:

```bash
Error: [speech-rule-engine@3.3.2 › speech-rule-engine@file:speech-rule-engine-3.3.2.tgz] resolved
target /path/to/temp/speech-rule-engine-3.3.2.tgz error: ENOENT:
no such file or directory, lstat '/path/to/temp/speech-rule-engine-3.3.2.tgz'
```

**Comment by zorkow** [comment]
Not sure what went wrong with the release last night. Oddly enough all the files seem to be there and the online version works fine: https://cdn.jsdelivr.net/npm/speech-rule-engine@latest/

I'll make a hot fix `3.3.3` release shortly.

**Comment by zorkow** [comment]
Please see my latest comments on #528

**Comment by PeachScript** [comment]
`3.3.3` works, thank you!

**Comment by zorkow** [comment]
Good. Still don't know what went wrong. The publishing log for 3.3.2 looks good.

**Comment by PeachScript** [comment]
> Good. Still don't know what went wrong. The publishing log for 3.3.2 looks good.

The package.json of 3.3.2 has an unexpected dependency called 'speech-rule-engine'(yep, it same as the package name), and it target a local tar file via 'file://' scheme, so I guess something wrong in pre-publish step from 3.3.2

You can check out the dependencies of https://unpkg.com/browse/speech-rule-engine@3.3.2/package.json
