### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by link-duan** [zorkow/speech-rule-engine#528]
error "speech-rule-engine-3.3.2.tgz": Tarball is not in network and can not be located in cache ...

**Comment by link-duan** [comment]
![image](https://user-images.githubusercontent.com/20787331/121623978-43265e00-caa3-11eb-8de7-db8f1a8b91b8.png)

**Comment by Curitis** [comment]
same problem

**Comment by surmrf** [comment]
same problem

**Comment by Saber2pr** [comment]
same problem

**Comment by mytEcust** [comment]
same problem

**Comment by qingbozhang** [comment]
+1

**Comment by shlroland** [comment]
+1

**Comment by jiechud** [comment]
+1

**Comment by yeaaaling** [comment]
same problem

**Comment by yeaaaling** [comment]
how to resolve this problem

**Comment by yedegesong** [comment]
same problem

**Comment by shlroland** [comment]
@zorkow

**Comment by lincolnzhou** [comment]
same problem

**Comment by muyiyang1** [comment]
+1

**Comment by youngjuning** [comment]
Help. SOS.

**Comment by Saber2pr** [comment]
try to add it to package.json
```json
"resolutions": {
    "speech-rule-engine": "3.3.1"
  }
```

**Comment by bartvanraaij** [comment]
Had the same problem while trying to `npm install -D @marp-team/marp-cli`.
Fixed by running `npm i -D speech-rule-engine@3.3.1` first.

I now have speech-rule-engine as a project dependency, which is not what I want, but at least I can continue my work.

**Comment by zorkow** [comment]
Not sure what went wrong with the release last night. Oddly enough all the files seem to be there and the online version works fine: https://cdn.jsdelivr.net/npm/speech-rule-engine@latest/

I'll make a hot fix `3.3.3` release shortly.

**Comment by zorkow** [comment]
I've just made a `speech-rule-engine@3.3.3` release, which should fix the problem. It works for me on two different machines.
I've deprecated `speech-rule-engine@3.3.2` on npm.

Can anybody please give me feedback if it works for them as well?

**Comment by nttp-3110** [comment]
> I've just made a `speech-rule-engine@3.3.3` release, which should fix the problem. It works for me on two different machines.
> I've deprecated `speech-rule-engine@3.3.2` on npm.
> 
> Can anybody please give me feedback if it works for them as well?
npm package still use 3.3.2 version. And this show https://www.npmjs.com/package/speech-rule-engine

**Comment by nttp-3110** [comment]
@zorkow Can you update this hotfix in npmjs aswell?

**Comment by zorkow** [comment]
@nttp-3110 
https://www.npmjs.com/package/speech-rule-engine shows me 3.3.3. 
`npm install speech-rule-engine`  also installs `@3.3.3` for me.
Maybe it is caching issue for you. Can you try to reload the page after clearing you cache or in a private tab?

**Comment by zorkow** [comment]
SRE now installs fine via `npm`, `yarn`, `pnpm`, and `bower`. 
The changes have not yet propagated through `jsdelivr`, but the online version of `3.3.2` worked fine anyway.

Can anyone still see the problem?

**Comment by bartvanraaij** [comment]
Works for me now, thanks!
