### ISSUE TITLE
DOMexception for every expression

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#6]
I'm now getting

```
DOMException [HierarchyRequestError: "Node cannot be inserted at the specified point in the hierarchy"
code: 3
nsresult: 0x80530003
location: http://progressiveaccess.com/content/semantic.js:30]
```

for all expressions that I've tried.

**Comment by zorkow** [comment]
Clone problem?
PTAL

**Comment by dpvc** [comment]
It is in the `semantic.js` code, during the call to `sre.Semantic.enrichMathml()`, and not in my code.  It is occurring in code that worked yesterday (the test file I sent you earlier, which hasn't changed).  So I think it is something in what you did earlier today.

**Comment by zorkow** [comment]
I just uploaded a new version that should fix.
Works for me now.

**Comment by zorkow** [comment]
I have reimplemented the whole tree construction in a cleaner way to reduce on corner cases.
But forgot to introduce top level cloning. That only seems to matter in a browser, not in node.

**Comment by dpvc** [comment]
Works for me now.  Thanks!
