### ISSUE TITLE
Spacing elements are ignored (leading to inappropriate implicit multiplication)

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#9]
The TeX code `x\quad y` produces the MathML

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>x</mi>
  <mspace width="1em" />
  <mi>y</mi>
</math>
```

 which is enhanced as

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" type="infixop" role="implicit" id="3" children="0,1" content="2">
  <mi type="identifier" role="latinletter" id="0" parent="3">x</mi>
  <mo type="operator" role="multiplication" id="2" parent="3" added="true" operator="infixop,&#x2062;">&#x2062;</mo>
  <mi type="identifier" role="latinletter" id="1" parent="3">y</mi>
</math>
```

The original `\quad` is probably used to separate distinct expressions, so it is not really appropriate to mark this as multiplication.  Also, the space is lost, so the rendering of the enhanced version is incorrect.  We will need to maintain the spacing that is in the original equation.

**Comment by zorkow** [comment]
There are effectively two issues:
1) Keeping elements that are currently ignored by the semantic interpretation (mspace, mphantom, merror). That is easy and I know where and how to do it.

2) If we don't want an implicit multiplication here, which I fully agree is probably not the right interpretation, how do we want to interpret "x  y" then? Implicit punctuation?
How about an expression like a + b \quad x + y. The space could effectively stand for an invisible comma, hence the whole expression could be (, (+ a b) (+ x y))
This issue also means tinkering with the semantic tree representation, which could be a bit more involved.

**Comment by dpvc** [comment]
> 1) Keeping elements that are currently ignored by the semantic interpretation (mspace, mphantom, merror). That is easy and I know where and how to do it.

Great, as that is going to be important.  (E.g., the TeX input jax does use space and mphantom, so we are definitely going to see these.)

> 2) If we don't want an implicit multiplication here, ... how do we want to interpret `x y` then? Implicit punctuation?  

Well, if you mean `x y` in TeX, the space is ignored in the TeX conversion, so you just get `<mi>x</mi><mi>y</mi>`, and SRE will mark this as implicit multiplication, which I would say is correct.  But `x\,y`, `x\ y`, and `x\quad y` are a little less clear.  I would say the first should still be implied multiplication, and that the last probably should *not* be.  So it might depend on the *size* of the space (argh!).

> How about an expression like `a + b \quad x + y`. The space could effectively stand for an invisible comma, hence the whole expression could be `(, (+ a b) (+ x y))`

I guess that would be reasonable.  Is there a reason why there can't be some sort of space semantic-type?  There is also going to be *negative* space (from `\!`), and I don't think you want to make that an invisible comma.  There are also uses like `\sqrt{\,\ln(x)}` and `\int x\,dx` to get better spacing.  Spaces are also used to get colored boxes, as in `<mspace width="1em" height="1em" mathbackground="red" />` (`<mphantom>` is also used that way), and I'm not sure how that should be handled.

Spaces that become commas may only be appropriate if they are used "at the top level" (i.e., as children of the `<math>` tag (or inside elements like `<maction>`, `<semantics>`, `<mrow>`, and so on that are at the top level), or in `<mtd>` elements (but that's a whole other settle of fish).

Maybe you need a `semantic-type="ignore"`?

**Comment by zorkow** [comment]
The invisible comma was effectively used as a sort of semantic space type. I agree that it might be inappropriate for negative space. I used to have this type only on the top level and tables (for case statements mainly), but changed that in the course of the Benetech project, where small sentences appeared in fractions, subscripts etc.

>  There are also uses like \sqrt{\,\ln(x)} and \int x\,dx to get better spacing

Here I would argue that the spacing should be ignored as semantically irrelevant. What does MathJax do? Will you put an mspace there?

Using type punctuated with a space type as punctuation could work. It could get the role ignore. 
The type is thought of as the immutable part (not always true in the case of vertical lines for example).

**Comment by dpvc** [comment]
>  I used to have this type only on the top level and tables (for case statements mainly), but changed that in the course of the Benetech project, where small sentences appeared in fractions, subscripts etc.

You also see this type of thing in aligned equation output.

> Here I would argue that the spacing should be ignored as semantically irrelevant.

I agree.  I just want to be sure that the space isn't lost in the enriched MathML, as it is important for the displayed output.

> What does MathJax do? Will you put an mspace there?

Yes, it is an space.  Here is the output from MathJax:

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <msqrt>
    <mspace width="thinmathspace" />
    <mi>ln</mi>
    <mo>&#x2061;<!-- ⁡ --></mo>
    <mo stretchy="false">(</mo>
    <mi>x</mi>
    <mo stretchy="false">)</mo>
  </msqrt>
</math>
```

> Using type punctuated with a space type as punctuation could work. It could get the role ignore. 

That sounds reasonable.

**Comment by zorkow** [comment]
Particularly important for 
```XML
<mspace linebreak="newline" />
```

**Comment by zorkow** [comment]
In 3.2.0-beta.3
